### ISSUE TITLE
Wrong handling of keyword with quoted string argument in message body

### ISSUE THREAD

**Issue by McTrk** [SIPp/sipp#168]
Authentication Keyword in REGISTER message is as follows:
`      [authentication username="[field0]@[field1]" uri="sip:[field1]"]`

This line should be translated by SIPp into a header such as the following:

`Authorization: Digest username="user@ims.net",realm="ims.net",cnonce="6b8b4567",nc=00000001,qop="auth",uri="sip:ims.net",nonce="34...rV",response="cd...ce",algorithm=MD5,opaque="Z1...ZE"`

Faulty behavior: The Authorization header is missing and the client error trace contains:
`sipp: The following events occured:
2015-07-22	15:51:24.770028	1437598284.770028: Syntax error or invalid [keyword] in scenario while parsing ''.`

Fault seems to have been introduced in message.cpp / quoted_strchr(.,.) in May.

**Comment by vodik** [comment]
Thanks for the catch, what an embarrassing set of bugs. I'll add some test coverage to catch any further regressions on this logic.

**Comment by McTrk** [comment]
The working version is as follows:

'static char* quoted_strchr(const char* s, int c)
{   /* Like strchr, but don't count things in quotes. */
    const char* p;

    for (p = s; *p && *p != c; p++) {
        if (*p == '\"') {
	    do {
	        p++;
	    } while(*p && *p != '\"');
	}
    }

    return *p == c ? const_cast<char*>(p) : NULL ;
}'

**Comment by vodik** [comment]
Yeah, does the fix on master work?

~~~c
do {
    p++;
} while(*p && *p != '\"');
~~~

and

~~~c
p++;
p+= strcspn(p, "\"");
~~~

should be equivalent statements. What I had wrong was forgetting the `p++` so `strcspn` would return 0 since we're starting the search already on a `\"` character.

I was able to reproduce your problem and this made it go away, this was a corner case I missed in testing (though after seeing the other mistakes I made in here, I seriously wonder if any of my testing even covered this code path embarrassingly). I will add some test cases specifically for this function later tonight when I have some free time.

**Comment by McTrk** [comment]
I agree these should be equivalent. Tried the p++ ; str..., too. The result fails to replace the keyword with literal, inserts name in wrong place (beginning of line), places garbled characters in quotes.

Strcspn is relatively less known to me  compared to the `do { ... } while(...);` the behavior of which was much easier to predict and fix.

Following this loop was a redundant check in the original, `*p != NULL`, already covered  by `*p==c` in the return statement, and could be removed.

Thanks for the quick responses; this will save users a lot of trouble.

**Comment by vodik** [comment]
Yeah, I absolutely agree.

**Comment by dmbhatti** [comment]
Face occasionally with SIPp v3.7.2-TLS-SCTP-PCAP
