### ISSUE TITLE
missing version.h included from src/call.cpp

### ISSUE THREAD

**Issue by pwallis** [SIPp/sipp#190]
Just downloaded and ran ./build.sh and got the above message.  My C is quite rusty but I then tried removing the include line from call.cpp and got the same message.  I guess I have not read the instructions carefully enough ...
I will keep looking..

P

**Comment by wdoekes** [comment]
Hi there.

`include/version.h` is created automatically if you have a working git checkout.

If you however downloaded the zip file from the releases, it would not be included AND you would not be able to produce it.

Am I right in guessing that you downloaded on of these:
https://github.com/SIPp/sipp/archive/v3.5.0.zip
https://github.com/SIPp/sipp/archive/v3.5.0.tar.gz

Instead of this:
https://github.com/SIPp/sipp/releases/download/v3.5.0/sipp-3.5.0.tar.gz

That last one has the `include/version.h` included:
```
$ tar ztvf sipp-3.5.0.tar.gz | grep version.h
-rw-rw-r-- walter/walter     30 2016-02-08 23:00 sipp-3.5.0/include/version.h
```

**Comment by pwallis** [comment]
Yep. Thanks very much.  - not universal on git I assume...
P
