### ISSUE TITLE
incorrect order of [routes]

### ISSUE THREAD

**Issue by smititelu** [SIPp/sipp#262]
Hi,

I am starting SIPp as a UAS, with config file [1]. The problem I have, at BYE, is that [routes] append the "Route:" header with wrong content order, as below:

```
how it should look: Route:  <sip:172.16.38.75;lr=on;ftag=y96a53D52ZHXH>, <sip:172.16.38.63;lr;ftag=y96a53D52ZHXH>, <sip:172.16.38.53;lr=on;ftag=y96a53D52ZHXH>
how it looks: Route:  <sip:172.16.38.63;lr;ftag=y96a53D52ZHXH>, <sip:172.16.38.53;lr=on;ftag=y96a53D52ZHXH>,<sip:172.16.38.75;lr=on;ftag=y96a53D52ZHXH>
```

Should I do something in addition, or is this a bug?

[1] http://pastebin.com/fiFQKQK3

**Comment by wdoekes** [comment]
I haven't tested this, but I don't think this is necessarily a bug, but rather a "lack of feature".

If you'd run SIPp as an UAC, you want SIPp to put the Record-Route headers in reverse order into the `[routes]` set. I think SIPp has no idea whether it's UAS or UAC at that point and always simply stores them in reverse order.

The workaround for you would be to store the `[Record-Route:]` at incoming INVITE into a variable and use that instead of `[routes]`.

**Comment by wdoekes** [comment]
Okay. It was a bug after all :)

I think this should fix things.
