### ISSUE TITLE
Does sipp support binary message body ?

### ISSUE THREAD

**Issue by tigerych** [SIPp/sipp#281]
I'd like to use sipp tool to send body is a binary message. As following:
MESSAGE 
.........
Accept-Contact: *;+g.3gpp.smsip;require;explicit;[$1]
Content-Length: [len]
Content-Type: application/vnd.3gpp.sms

0108099164000309572500f0005c06080d91683195[$3][$2][$5][$4][$7][$6]f[$8]71104141240523711041412405230007000046547419d42ecfe7e17319947fd741f3b29b0ea2bf41385b0c8783c160b2992d2603a1c37390b85c7683c86576da5e9697c9a0797d3c2ecfe7e63a9b9d7701

Does sipp support it ?

**Comment by aaicken** [comment]
From memory I think you need to use \x before each byte if you want to include a binary message body, e.g. \x01\x08\x09\x91 etc. Hope that helps.

For future reference, you probably shouldn't raise an issue to ask a question as issues should just be used to track bugs and feature requests. It would have been better to ask a question first on the users mailing list rather than raising an issue here. You're also more likely to get a faster response.

**Comment by tigerych** [comment]
Hi,
       How can I ask questions on the users mailing list ?

Thks.

发件人: aaicken [mailto:notifications@github.com]
发送时间: 2017年2月10日 7:55
收件人: SIPp/sipp
抄送: Yechuanhu; Author
主题: Re: [SIPp/sipp] Does sipp support binary message body ? (#281)


From memory I think you need to use \x before each byte if you want to include a binary message body, e.g. \x01\x08\x09\x91 etc. Hope that helps.

For future reference, you probably shouldn't raise an issue to ask a question as issues should just be used to track bugs and feature requests. It would have been better to ask a question first on the users mailing list rather than raising an issue here. You're also more likely to get a faster response.

**Comment by aaicken** [comment]
Mailing list details are here:

https://lists.sourceforge.net/lists/listinfo/sipp-users

**Comment by wdoekes** [comment]
Assuming this can be closed.

Possibly a candidate for a FAQ if that were to be created.
