### ISSUE TITLE
Error in SSL connection: SSL_read returned SSL_ERROR_WANT_WRITE

### ISSUE THREAD

**Issue by rysj** [SIPp/sipp#293]
TLS connection fails occasionally with SSL_ERROR_WANT_WRITE returned from SSL_connect (in socket.cpp). 

According to https://www.openssl.org/docs/man1.0.2/ssl/SSL_get_error.html TLS/SSL I/O function should be retried on this error

**Comment by wdoekes** [comment]
Thanks for the bug report.

If you make a PR, we can speed up getting a fix in.

**Comment by rysj** [comment]
I think the problem has been already addressed by https://github.com/SIPp/sipp/commit/d98248c1a643e13b2702b3f378ed75953ed3d8a7

**Comment by sgel83** [comment]
Yes this has been addressed. I was also hitting this error quite often and a colleague of mine fixed it. I do not hit it anymore except if you do a localhost to localhost connection at high load, but I think that just is because that the transactions are happening faster then the crypto calcuation for the session can take place.

**Comment by wdoekes** [comment]
Good. Closing for now. Thanks for the updates!
