### ISSUE TITLE
Using SIPp as UAS behind a NAT

### ISSUE THREAD

**Issue by anilkumar27** [SIPp/sipp#385]
am running 2 SIPp scripts, one for Registration and other for receiving incoming calls(invite) but both listening to same port.

Registration works fine but am not able to receive incoming sip messages for my incoming SIPp script because of NAT binding with the port which SIPp is running .

So how do i run both these scripts such that same NAT port will bind with SIPp port ?

**Comment by wdoekes** [comment]
Does not work simultaneously right now.

The easy fix would be:
- run a listening sipp on one port
- run a registering sipp on another where you specify the port from the other sipp in the Contact

But, that doesn't work when you have NAT, because you don't know where the listening port will listen at.

The alternative fix is to run the two sipp's consecutively:
- run registering-sipp and let it finish; specify a port explicitly
- run the listening-sipp on the same port

Closing as this is a support question.
